// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TonVinhHienMau.Data;

namespace TonVinhHienMau.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220514011456_Db")]
    partial class Db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TonVinhHienMau.Models.DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diachi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDonVi")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("DonVi");
                });

            modelBuilder.Entity("TonVinhHienMau.Models.DotTonVinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDotTonVinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDotTonVinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("DotTonVinh");
                });

            modelBuilder.Entity("TonVinhHienMau.Models.NguoiHienMau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("DonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DotTonVinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NamSinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NamTV_10")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_100")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_15")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_20")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_30")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_40")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_5")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_50")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_60")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_70")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_80")
                        .HasColumnType("int");

                    b.Property<int>("NamTV_90")
                        .HasColumnType("int");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TV_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_70")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_80")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_90")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.HasIndex("DotTonVinhId");

                    b.ToTable("NguoiHienMau");
                });

            modelBuilder.Entity("TonVinhHienMau.Models.NguoiHienMau", b =>
                {
                    b.HasOne("TonVinhHienMau.Models.DonVi", "DonVis")
                        .WithMany()
                        .HasForeignKey("DonViId");

                    b.HasOne("TonVinhHienMau.Models.DotTonVinh", "DotTonVinh")
                        .WithMany()
                        .HasForeignKey("DotTonVinhId");

                    b.Navigation("DonVis");

                    b.Navigation("DotTonVinh");
                });
#pragma warning restore 612, 618
        }
    }
}
